const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/ootitemtracker"
);

const areaSeed = [
  {
    name: "kokiriForest",
    title: "Kokiri Forest",
    top: "425px",
    left: "950px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "dekuTree",
    title: "Deku Tree",
    top: "350px",
    left: "1100px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "lostWoods",
    title: "Lost Woods",
    top: "325px",
    left: "925px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "hyruleField",
    title: "Hyrule Field",
    top: "350px",
    left: "650px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "lonlonRanch",
    title: "Lon Lon Ranch",
    top: "225px",
    left: "575px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "hyruleMarket",
    title: "Hyrule Market",
    top: "155px",
    left: "600px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "kakVillage",
    title: "Kakariko Village",
    top: "155px",
    left: "775px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "graveyard",
    title: "Graveyard",
    top: "160px",
    left: "875px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "deathMountain",
    title: "Death Mountain",
    top: "100px",
    left: "750px",
    requiredItems: ["bombs"],
    alternateItems: ["zeldasLetter"],
    isAccessible: false,
  },
  {
    name: "goronCity",
    title: "Goron City",
    top: "60px",
    left: "800px",
    requiredItems: ["bombs"],
    alternateItems: ["zeldasLetter"],
    isAccessible: true,
  },
  {
    name: "dodongosCavern",
    title: "Dodongo's Cavern",
    top: "60px",
    left: "740px",
    requiredItems: ["strength1"],
    alternateItems: ["bombs"],
    isAccessible: false,
  },
  {
    name: "zorasRiver",
    title: "Zora's River",
    top: "225px",
    left: "925px",
    requiredItems: ["bombs"],
    alternateItems: ["silverScale"],
    isAccessible: false,
  },
  {
    name: "zorasDomain",
    title: "Zora's Domain",
    top: "175px",
    left: "1150px",
    requiredItems: ["ocarina", "lullaby"],
    alternateItems: ["silverScale"],
    isAccessible: false,
  },
  {
    name: "jabu",
    title: "Jabu Jabu",
    top: "125px",
    left: "1125px",
    requiredItems: ["ocarina", "lullaby", "bottle1", "rutosLetter"],
    alternateItems: ["silverScale", "bottle1", "rutosLetter"],
    isAccessible: false,
  },
  {
    name: "lakeHylia",
    title: "Lake Hylia",
    top: "550px",
    left: "455px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "forestTemple",
    title: "Forest Temple",
    top: "275px",
    left: "950px",
    requiredItems: ["hookshot", "ocarina", "minuet", "saria"],
    alternateItems: ["hookshot", "ocarina", "saria"],
    isAccessible: false,
  },
  {
    name: "fireTemple",
    title: "Fire Temple",
    top: "20px",
    left: "790px",
    requiredItems: ["redTunic", "hookshot"],
    alternateItems: ["redTunic", "ocarina", "bolero"],
    isAccessible: false,
  },
  {
    name: "iceCavern",
    title: "Ice Cavern",
    top: "100px",
    left: "1150px",
    requiredItems: ["rutosLetter", "silverScale", "ocarina", "lullaby"],
    alternateItems: ["rutosLetter", "silverScale"],
    isAccessible: false,
  },
  {
    name: "waterTemple",
    title: "Water Temple",
    top: "640px",
    left: "440px",
    requiredItems: ["hookshot", "ironBoots", "blueTunic"],
    alternateItems: [],
    isAccessible: false,
  },
  {
    name: "bottomOfTheWell",
    title: "Bottom of the Well",
    top: "155px",
    left: "825px",
    requiredItems: ["ocarina", "songOfStorms"],
    alternateItems: [],
    isAccessible: false,
  },
  {
    name: "shadowTemple",
    title: "Shadow Temple",
    top: "150px",
    left: "930px",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth"],
    alternateItems: [],
    isAccessible: false,
  },
  {
    name: "gerudoValley",
    title: "Gerudo Valley",
    top: "250px",
    left: "300px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "gerudoTrainingGround",
    title: "Gerudo Training Ground",
    top: "175px",
    left: "270px",
    requiredItems: ["longshot"],
    alternateItems: ["ocarina", "epona"],
    isAccessible: true,
  },
  {
    name: "desert",
    title: "Desert Wasteland/Oasis",
    top: "175px",
    left: "120px",
    requiredItems: ["ocarina", "requiem"],
    alternateItems: ["longshot", "lensOfTruth", "magic1"],
    isAccessible: false,
  },
  {
    name: "spiritTemple",
    title: "Sprit Temple",
    top: "140px",
    left: "15px",
    requiredItems: ["ocarina", "requiem"],
    alternateItems: ["longshot", "lensOfTruth", "magic1"],
    isAccessible: false,
  },
  {
    name: "ganonsCastle",
    title: "Ganon's Castle",
    top: "60px",
    left: "625px",
    requiredItems: ["forestMedallion", "fireMedallion", "waterMedallion", "shadowMedallion", "spiritMedallion", "lightMedallion"],
    alternateItems: [],
    isAccessible: false,
  },
];

db.Area.remove({})
  .then(() => db.Area.collection.insertMany(areaSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted.");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
