const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/ootitemtracker"
);

const areaSeed = [
  {
    name: "kokiriForest",
    title: "Kokiri Forest",
    top: "425px",
    left: "950px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "dekuTree",
    title: "Deku Tree",
    top: "350px",
    left: "1100px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "lostWoods",
    title: "Lost Woods",
    top: "325px",
    left: "925px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "hyruleField",
    title: "Hyrule Field",
    top: "350px",
    left: "650px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "lonlonRanch",
    title: "Lon Lon Ranch",
    top: "225px",
    left: "575px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "hyruleMarket",
    title: "Hyrule Market",
    top: "155px",
    left: "600px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "kakVillage",
    title: "Kakariko Village",
    top: "155px",
    left: "775px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "graveyard",
    title: "Graveyard",
    top: "160px",
    left: "875px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "deathMountain",
    title: "Death Mountain",
    top: "100px",
    left: "750px",
    requiredItems: ["bombs"],
    alternateItems: ["zeldasLetter"],
    isAccessible: false,
  },
  {
    name: "goronCity",
    title: "Goron City",
    top: "60px",
    left: "800px",
    requiredItems: ["bombs"],
    alternateItems: ["zeldasLetter"],
    isAccessible: true,
  },
  {
    name: "dodongosCavern",
    title: "Dodongo's Cavern",
    top: "60px",
    left: "740px",
    requiredItems: ["strength1"],
    alternateItems: ["bombs"],
    isAccessible: false,
  },
  {
    name: "zorasRiver",
    title: "Zora's River",
    top: "225px",
    left: "925px",
    requiredItems: ["bombs"],
    alternateItems: ["silverScale"],
    isAccessible: false,
  },
  {
    name: "zorasDomain",
    title: "Zora's Domain",
    top: "175px",
    left: "1150px",
    requiredItems: ["ocarina", "lullaby"],
    alternateItems: ["silverScale"],
    isAccessible: false,
  },
  {
    name: "jabu",
    title: "Jabu Jabu",
    top: "125px",
    left: "1125px",
    requiredItems: ["ocarina", "lullaby", "bottle1", "rutosLetter"],
    alternateItems: ["silverScale", "bottle1", "rutosLetter"],
    isAccessible: false,
  },
  {
    name: "lakeHylia",
    title: "Lake Hylia",
    top: "550px",
    left: "455px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "forestTemple",
    title: "Forest Temple",
    top: "275px",
    left: "950px",
    requiredItems: ["hookshot", "ocarina", "minuet"],
    alternateItems: ["hookshot", "ocarina", "saria"],
    isAccessible: false,
  },
  {
    name: "fireTemple",
    title: "Fire Temple",
    top: "20px",
    left: "790px",
    requiredItems: ["redTunic", "hookshot"],
    alternateItems: ["redTunic", "ocarina", "bolero"],
    isAccessible: false,
  },
  {
    name: "iceCavern",
    title: "Ice Cavern",
    top: "100px",
    left: "1150px",
    requiredItems: ["rutosLetter", "bombs", "ocarina", "lullaby"],
    alternateItems: ["rutosLetter", "silverScale"],
    isAccessible: false,
  },
  {
    name: "waterTemple",
    title: "Water Temple",
    top: "640px",
    left: "440px",
    requiredItems: ["hookshot", "ironBoots", "blueTunic"],
    alternateItems: [],
    isAccessible: false,
  },
  {
    name: "bottomOfTheWell",
    title: "Bottom of the Well",
    top: "155px",
    left: "825px",
    requiredItems: ["ocarina", "songOfStorms"],
    alternateItems: [],
    isAccessible: false,
  },
  {
    name: "shadowTemple",
    title: "Shadow Temple",
    top: "150px",
    left: "930px",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth"],
    alternateItems: [],
    isAccessible: false,
  },
  {
    name: "gerudoValley",
    title: "Gerudo Valley",
    top: "250px",
    left: "300px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: true,
  },
  {
    name: "gerudoTrainingGround",
    title: "Gerudo Training Ground",
    top: "175px",
    left: "270px",
    requiredItems: ["longshot"],
    alternateItems: ["ocarina", "epona"],
    isAccessible: true,
  },
  {
    name: "desert",
    title: "Desert Wasteland/Oasis",
    top: "175px",
    left: "120px",
    requiredItems: ["ocarina", "requiem"],
    alternateItems: ["longshot", "lensOfTruth", "magic1"],
    isAccessible: false,
  },
  {
    name: "spiritTemple",
    title: "Sprit Temple",
    top: "140px",
    left: "15px",
    requiredItems: ["ocarina", "requiem"],
    alternateItems: ["longshot", "lensOfTruth", "magic1"],
    isAccessible: false,
  },
  {
    name: "ganonsCastle",
    title: "Ganon's Castle",
    top: "60px",
    left: "625px",
    requiredItems: [],
    alternateItems: [],
    isAccessible: false,
  },
];

const checkSeed = [
  {
    name: "midosHouse",
    title: "Mido's House (4)",
    location: "kokiriForest",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "swordCheck",
    title: "Kokiri Sword Chest",
    location: "kokiriForest",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "songOfStormsGrotto",
    title: "Song of Storms Grotto",
    location: "kokiriForest",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "ocarinaCheck",
    title: "Fairy Ocarina",
    location: "kokiriForest",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "dekuMap",
    title: "Map Chest",
    location: "dekuTree",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "dekuCompass",
    title: "Compass Chest",
    location: "dekuTree",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "compassChestSide",
    title: "Compass Room Side Chest",
    location: "dekuTree",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "slingshotCheck",
    title: "Slingshot Chest",
    location: "dekuTree",
    color: "red",
    requiredItems: ["dekuShield"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "slingshotChestSide",
    title: "Slingshot Side Chest",
    location: "dekuTree",
    color: "red",
    requiredItems: ["dekuShield"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "ghoma",
    title: "Ghoma",
    location: "dekuTree",
    color: "red",
    requiredItems: ["dekuShield", "slingShot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "skullKid",
    title: "Skull Kid",
    location: "lostWoods",
    color: "red",
    requiredItems: ["ocarina", "saria"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "scrub",
    title: "Scrub Salesman",
    location: "lostWoods",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "memoryGame",
    title: "Ocarina Memory Game",
    location: "lostWoods",
    color: "red",
    requiredItems: ["ocarina"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "slingshotTarget",
    title: "Slingshot Target",
    location: "lostWoods",
    color: "red",
    requiredItems: ["slingShot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lostWoodsBombGrotto",
    title: "Bomb Grotto",
    location: "lostWoods",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "scrubGrotto",
    title: "Scrub Salesman Grotto",
    location: "lostWoods",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "wolfosGrotto",
    title: "Wolfos Grotto",
    location: "lostWoods",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["bombchus"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "sariaSong",
    title: "Saria's Song",
    location: "lostWoods",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "minuetOfForest",
    title: "Minuet of Forest",
    location: "lostWoods",
    color: "red",
    requiredItems: ["ocarina", "saria"],
    secondaryItems: ["ocarina", "minuet"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "skullMask",
    title: "Deku Theater Skull Mask",
    location: "lostWoods",
    color: "red",
    requiredItems: ["skullMask"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "maskOfTruth",
    title: "Deku Theater Mask of Truth",
    location: "lostWoods",
    color: "red",
    requiredItems: ["maskOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "southGrotto",
    title: "South Grotto",
    location: "hyruleField",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "southScrubGrotto",
    title: "South Scrub Salesman Grotto",
    location: "hyruleField",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "southEastGrotto",
    title: "Southeast Grotto",
    location: "hyruleField",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "northWestGrotto",
    title: "Northwest Grotto",
    location: "hyruleField",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "northGrotto",
    title: "North Grotto",
    location: "hyruleField",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "songOfTimeCheck",
    title: "Song of Time",
    location: "hyruleField",
    color: "red",
    requiredItems: ["emerald", "ruby", "sapphire"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "ocarinaOfTimeCheck",
    title: "Ocarina of Time",
    location: "hyruleField",
    color: "red",
    requiredItems: ["emerald", "ruby", "sapphire"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "eponasSong",
    title: "Epona's Song",
    location: "lonlonRanch",
    color: "red",
    requiredItems: ["ocarina"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "chickenGame",
    title: "Cucco Game",
    location: "lonlonRanch",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "lonlonHeartPiece",
    title: "Lon Lon Heart Piece",
    location: "lonlonRanch",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "lullabyCheck",
    title: "Zelda's Lullaby",
    location: "hyruleMarket",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "childGallery",
    title: "Child Shooting Gallery",
    location: "hyruleMarket",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "bombchuBowling1",
    title: "Bombchu Bowling 1",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "bombchuBowling2",
    title: "Bombchu Bowling 2",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "chestGame",
    title: "Chest Game",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["lensOfTruth", "magic1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "dogLady",
    title: "Return Monty the Dog",
    location: "hyruleMarket",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "10Poes",
    title: "10 Big Poes",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["bow", "epona", "bottle1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "dinsFireCheck",
    title: "Din's Fire",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["bombs", "ocarina", "lullaby"],
    secondaryItems: ["hammer", "ocarina", "lullaby"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "healthUpgrade",
    title: "Health Upgrade",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["ocarina", "lullaby", "strength3"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "preludeCheck",
    title: "Prelude of Light",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["forestMedallion"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightArrowCheck",
    title: "Light Arrow Check",
    location: "hyruleMarket",
    color: "red",
    requiredItems: ["forestMedallion", "fireMedallion", "waterMedallion", "shadowMedallion", "spiritMedallion", "lightMedallion"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "childChickens",
    title: "Collect Cuccos",
    location: "kakVillage",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "anju",
    title: "Anju as Adult",
    location: "kakVillage",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "BackGrottoChest",
    title: "Back Grotto",
    location: "kakVillage",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "redeadGrotto",
    title: "Redead Grotto",
    location: "kakVillage",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["bombchus"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "cowCheck",
    title: "Cow House",
    location: "kakVillage",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "manOnRoof",
    title: "Guy on the Roof",
    location: "kakVillage",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "adultGallery",
    title: "Adult Shooting Gallery",
    location: "kakVillage",
    color: "red",
    requiredItems: ["bow"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "songOfStormsCheck",
    title: "Song of Storms",
    location: "kakVillage",
    color: "red",
    requiredItems: ["ocarina"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "windmillHeartPiece",
    title: "Windmill Heat Piece",
    location: "kakVillage",
    color: "red",
    requiredItems: ["ocarina", "songOfTime"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "nocturnCheck",
    title: "Nocturn of Shadow",
    location: "kakVillage",
    color: "red",
    requiredItems: ["forestMedallion", "fireMedallion", "waterMedallion"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "skull10Check",
    title: "10 Gold Skulltulas",
    location: "kakVillage",
    color: "red",
    requiredItems: ["skull10"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "skull20Check",
    title: "20 Gold Skulltulas",
    location: "kakVillage",
    color: "red",
    requiredItems: ["skull20"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "skull30Check",
    title: "30 Gold Skulltulas",
    location: "kakVillage",
    color: "red",
    requiredItems: ["skull30"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "skull40Check",
    title: "40 Gold Skulltulas",
    location: "kakVillage",
    color: "red",
    requiredItems: ["skull40"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "skull50Check",
    title: "50 Gold Skulltulas",
    location: "kakVillage",
    color: "red",
    requiredItems: ["skull50"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "dampe1",
    title: "Dampe Race 1",
    location: "graveyard",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "dampe2",
    title: "Dampe Race 2",
    location: "graveyard",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "dampeHeartPiece",
    title: "Dampe Heart Piece",
    location: "graveyard",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "redeadGrave",
    title: "Redead Grave",
    location: "graveyard",
    color: "red",
    requiredItems: ["sunSong"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "sunSongCheck",
    title: "Sun Song",
    location: "graveyard",
    color: "red",
    requiredItems: ["ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "sunSongChest",
    title: "Sun Song Chest",
    location: "graveyard",
    color: "red",
    requiredItems: ["ocarina", "lullaby", "magic1", "dinsFire"],
    secondaryItems: ["ocarina", "lullaby", "magic1", "fireArrow"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "boxHeartPiece",
    title: "Boxed Heart Piece",
    location: "graveyard",
    color: "red",
    requiredItems: ["longshot"],
    secondaryItems: ["beans"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "leftMaze",
    title: "Left Boulder Maze",
    location: "goronCity",
    color: "red",
    requiredItems: ["hammer"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "centerMaze",
    title: "Center Boulder Maze",
    location: "goronCity",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["strength1"],
    ternaryItems: ["hammer"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "rightMaze",
    title: "Right Boulder Maze",
    location: "goronCity",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["strength1"],
    ternaryItems: ["hammer"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hotRodder",
    title: "Hot Rodder Goron",
    location: "goronCity",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["bombchus"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "linkTheGoron",
    title: "Link The Goron",
    location: "goronCity",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "spinningPot",
    title: "Spinning Pot Heart Piece",
    location: "goronCity",
    color: "red",
    requiredItems: ["bombs", "ocarina", "lullaby"],
    secondaryItems: ["ocarina", "lullaby"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "daruniasJoy",
    title: "Darunia's Joy",
    location: "goronCity",
    color: "red",
    requiredItems: [ "ocarina", "lullaby", "saria"],
    secondaryItems: [ ],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "dodongoHeartPiece",
    title: "Above Dodongo's Cavern Heart",
    location: "deathMountain",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "wallChest",
    title: "Chest in Wall",
    location: "deathMountain",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: ["bombchus"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "outsideGoronCityGrotto",
    title: "Outside Goron City Grotto",
    location: "deathMountain",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "boleroCheck",
    title: "Bolero of Fire",
    location: "deathMountain",
    color: "red",
    requiredItems: ["bombs", "hookshot"],
    secondaryItems: ["ocarina", "bolero"],
    ternaryItems: ["hammer", "hookshot"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "craterHeartPiece",
    title: "Crater Wall Heart Piece",
    location: "deathMountain",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "magic1Check",
    title: "Magic Upgrade 1",
    location: "deathMountain",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "magic2Check",
    title: "Magic Upgrade 2",
    location: "deathMountain",
    color: "red",
    requiredItems: ["hammer"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "craterBeanHeartPiece",
    title: "Crater Magic Bean Heart Piece",
    location: "deathMountain",
    color: "red",
    requiredItems: ["bombs", "hookshot", "beans"],
    secondaryItems: ["ocarina", "bolero", "beans"],
    ternaryItems: ["hammer", "hookshot", "beans"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "craterGrotto",
    title: "Crater Grotto",
    location: "deathMountain",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: ["bombchus"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "bigGoronSword",
    title: "Big Goron Sword",
    location: "deathMountain",
    color: "red",
    requiredItems: ["claimCheck"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "dodongoMap",
    title: "Map Chest",
    location: "dodongosCavern",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["strength1"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "dodongoCompass",
    title: "Compass Chest",
    location: "dodongosCavern",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["strength1"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "bombPlatform",
    title: "Platform Before Bombs",
    location: "dodongosCavern",
    color: "red",
    requiredItems: ["bombs", "slingshot"],
    secondaryItems: ["strength1", "slingshot"],
    ternaryItems: ["bombs", "bow"],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "bombBagChest",
    title: "Bomb Bag Chest",
    location: "dodongosCavern",
    color: "red",
    requiredItems: ["bombs", "slingshot"],
    secondaryItems: ["strength1", "slingshot"],
    ternaryItems: ["bombs", "bow"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "endOfBridgeChest",
    title: "End of Bridge Chest",
    location: "dodongosCavern",
    color: "red",
    requiredItems: ["bombs", "slingshot"],
    secondaryItems: ["strength1", "slingshot"],
    ternaryItems: ["bombs", "bow"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "chestAboveDodongo",
    title: "Chest Above King Dodongo",
    location: "dodongosCavern",
    color: "red",
    requiredItems: ["bombs", "slingshot"],
    secondaryItems: ["strength1", "slingshot"],
    ternaryItems: ["bombs", "bow"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "kingDodongo",
    title: "King Dodongo",
    location: "dodongosCavern",
    color: "red",
    requiredItems: ["bombs", "slingshot"],
    secondaryItems: ["strength1", "slingshot"],
    ternaryItems: ["bombs", "bow"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "riverGrotto",
    title: "River Grotto",
    location: "zorasRiver",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: ["silverScale"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "southHeartPiece",
    title: "South HeartPiece",
    location: "zorasRiver",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: ["silverScale"],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "northHeartPiece",
    title: "North HeartPiece",
    location: "zorasRiver",
    color: "red",
    requiredItems: ["bombs"],
    secondaryItems: ["hammer"],
    ternaryItems: ["silverScale"],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "frogs1",
    title: "Frogs (Song of Storms)",
    location: "zorasRiver",
    color: "red",
    requiredItems: ["bombs", "ocarina", "songOfStorms"],
    secondaryItems: ["hammer", "ocarina", "songOfStorms"],
    ternaryItems: ["silverScale", "ocarina", "songOfStorms"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "frogs2",
    title: "Frogs (songs)",
    location: "zorasRiver",
    color: "red",
    requiredItems: ["bombs", "ocarina", "lullaby", "epona", "songOfTime", "sunSong"],
    secondaryItems: ["hammer", "ocarina", "lullaby", "epona", "songOfTime", "sunSong"],
    ternaryItems: ["silverScale", "ocarina", "lullaby", "epona", "songOfTime", "sunSong"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "divingMinigame",
    title: "Diving Minigame",
    location: "zorasDomain",
    color: "red",
    requiredItems: ["silverScale"],
    secondaryItems: ["bombs", "ocarina", "lullaby"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "kingZora",
    title: "King Zora Thawed",
    location: "zorasDomain",
    color: "red",
    requiredItems: ["bombs", "ocarina", "lullaby", "rutosNote"],
    secondaryItems: ["hammer", "ocarina", "lullaby", "rutosNote"],
    ternaryItems: ["bombchus", "ocarina", "lullaby", "rutosNote"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "torchRun",
    title: "Torch Run",
    location: "zorasDomain",
    color: "red",
    requiredItems: ["silverScale"],
    secondaryItems: ["bombs", "ocarina", "lullaby"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "faroresWindCheck",
    title: "Zora Fairy Fountain",
    location: "zorasFountain",
    color: "red",
    requiredItems: ["bombs", "rutosNote", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "iceBerg",
    title: "Iceberg Heart Piece",
    location: "zorasFountain",
    color: "red",
    requiredItems: ["bombs", "rutosNote", "ocarina", "lullaby"],
    secondaryItems: ["hammer", "rutosNote", "ocarina", "lullaby"],
    ternaryItems: ["silverScale", "rutosNote", "ocarina", "lullaby"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "underWaterHeartPiece",
    title: "Under Water Heart Piece",
    location: "zorasFountain",
    color: "red",
    requiredItems: ["bombs", "rutosNote", "ocarina", "lullaby", "ironBoots"],
    secondaryItems: ["hammer", "rutosNote", "ocarina", "lullaby", "ironBoots"],
    ternaryItems: ["silverScale", "rutosNote", "ocarina", "lullaby", "ironBoots"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "boomerangCheck",
    title: "Boomerang Chest",
    location: "jabu",
    color: "red",
    requiredItems: ["ocarina", "lullaby", "bottle1", "rutosLetter"],
    alternateItems: ["silverScale", "bottle1", "rutosLetter"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "jabuMap",
    title: "Map Chest",
    location: "jabu",
    color: "red",
    requiredItems: ["ocarina", "lullaby", "bottle1", "rutosLetter", "boomeraing"],
    alternateItems: ["silverScale", "bottle1", "rutosLetter", "boomeraing"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "jabuCompass",
    title: "Compass Chest",
    location: "jabu",
    color: "red",
    requiredItems: ["ocarina", "lullaby", "bottle1", "rutosLetter", "boomeraing"],
    alternateItems: ["silverScale", "bottle1", "rutosLetter", "boomeraing"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "barinade",
    title: "Barinade",
    location: "jabu",
    color: "red",
    requiredItems: ["ocarina", "lullaby", "bottle1", "rutosLetter", "boomeraing"],
    alternateItems: ["silverScale", "bottle1", "rutosLetter", "boomeraing"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fireArrowCheck",
    title: "Fire Arrows",
    location: "lakeHylia",
    color: "red",
    requiredItems: ["bow"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "rutosBottleCheck",
    title: "Ruto's Bottle",
    location: "lakeHylia",
    color: "red",
    requiredItems: ["silverScale"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "bottomOfTheLab",
    title: "Bottom of the Lab",
    location: "lakeHylia",
    color: "red",
    requiredItems: ["goldScale"],
    secondaryItems: ["hookshot", "ironBoots"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "childFishing",
    title: "Child Fishing",
    location: "lakeHylia",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "adultFishing",
    title: "Adult Fishing",
    location: "lakeHylia",
    color: "red",
    requiredItems: ["ocarina", "hookshot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "lobbyChest",
    title: "First Lobby Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "chestBehindLobby",
    title: "Chest Behind the Lobby",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet"],
    secondaryItems: ["hookshot", "ocarina", "saria"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "wellChest",
    title: "Well Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet"],
    secondaryItems: ["hookshot", "ocarina", "saria"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "forestMapChest",
    title: "Map Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet"],
    secondaryItems: ["hookshot", "ocarina", "saria"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "forrestCompass",
    title: "Compass Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet"],
    secondaryItems: ["hookshot", "ocarina", "saria"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "outdoorHookshot",
    title: "Outdoor Chest on the Hill",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fallingRoomChest",
    title: "Falling Ceiling Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "forrestBossKey",
    title: "Boss Key Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "blockPushChest",
    title: "Block Pushing Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "floorMasterChest",
    title: "Floor Master Room",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "bowCheck",
    title: "Bow Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "redPoe",
    title: "Red Poe Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "bluePoe",
    title: "Blue Poe Chest",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "bossRoomChest",
    title: "Chest Outside Boss Room",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "phantomGanon",
    title: "Phantom Ganon",
    location: "forestTemple",
    color: "red",
    requiredItems: ["hookshot", "ocarina", "minuet", "bow", "strength1"],
    secondaryItems: ["hookshot", "ocarina", "saria", "bow", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "chestNearBoss",
    title: "Chest Near Boss",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot"],
    alternateItems: ["redTunic", "ocarina", "bolero"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "flareDancerChest",
    title: "Flare Dancer Chest",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "hammer"],
    alternateItems: ["redTunic", "ocarina", "bolero", "hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fireBossKey",
    title: "Boss Key",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "hammer"],
    alternateItems: ["redTunic", "ocarina", "bolero", "hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lavaRoomLeftChest",
    title: "Lava Room Left Chest",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot"],
    alternateItems: ["redTunic", "ocarina", "bolero"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lavaRoomRightChest",
    title: "Lava Room Right Chest",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "bombs"],
    alternateItems: ["redTunic", "ocarina", "bolero", "bombs"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "boulderMazeLower",
    title: "Lower Boulder Maze",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "BoulderMazeUpper",
    title: "Upper Boulder Maze",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "BoulderMazeSide",
    title: "Side/Upper Boulder Maze",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "BoulderMazePit",
    title: "Boulder Maze Bombable Pit",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1", "bombs"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1", "bombs"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "scarecrowChest",
    title: "Scarecrow Upper Chest",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1", "ocarina"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1", "ocarina"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fireMap",
    title: "Map Chest",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fireCompass",
    title: "Fire Compass",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "highestGoronChest",
    title: "Highest Goron Chest",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1", "songOfTime", "hammer"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1", "songOfTime", "hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hammerCheck",
    title: "Hammer Chest",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1", "bombs"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1", "bombs"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "volvagia",
    title: "Volvagia",
    location: "fireTemple",
    color: "red",
    requiredItems: ["redTunic", "hookshot", "strength1", "bombs", "hammer"],
    alternateItems: ["redTunic", "ocarina", "bolero", "strength1", "bombs", "hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "iceMap",
    title: "Map Chest",
    location: "iceCavern",
    color: "red",
    requiredItems: ["rutosLetter", "bombs", "ocarina", "lullaby"],
    alternateItems: ["rutosLetter", "silverScale"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "iceCompass",
    title: "Compass Chest",
    location: "iceCavern",
    color: "red",
    requiredItems: ["rutosLetter", "bombs", "ocarina", "lullaby"],
    alternateItems: ["rutosLetter", "silverScale"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "iceHeartPiece",
    title: "Ice Cavern Heart Piece",
    location: "iceCavern",
    color: "red",
    requiredItems: ["rutosLetter", "bombs", "ocarina", "lullaby"],
    alternateItems: ["rutosLetter", "silverScale"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "ironBootsCheck",
    title: "Iron Boots",
    location: "iceCavern",
    color: "red",
    requiredItems: ["rutosLetter", "bombs", "ocarina", "lullaby"],
    alternateItems: ["rutosLetter", "silverScale"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "serenadeCheck",
    title: "Serenade of Water",
    location: "iceCavern",
    color: "red",
    requiredItems: ["rutosLetter", "bombs", "ocarina", "lullaby"],
    alternateItems: ["rutosLetter", "silverScale"],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "waterMap",
    title: "Map Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "waterCompass",
    title: "Compass Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "torchChest",
    title: "Torch Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic", "bow", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "dragonChest",
    title: "Dragon Room Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic", "ocarina", "lullaby", "songOfTime"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "centralTargetChest",
    title: "Central Bow Target Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic", "strength1", "longshot", "bow", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "waterBossKey",
    title: "Boss Key",
    location: "waterTemple",
    color: "red",
    requiredItems: ["ironBoots", "blueTunic", "strength1", "longshot", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "centralPillarChest",
    title: "Central Pillar Sunken Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "crackedWallChest",
    title: "Cracked Wall Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic", "ocarina", "lullaby", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "darkLink",
    title: "Dark Link",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "riverChest",
    title: "River Chest",
    location: "waterTemple",
    color: "red",
    requiredItems: ["hookshot", "ironBoots", "blueTunic", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "morpha",
    title: "Morpha",
    location: "waterTemple",
    color: "red",
    requiredItems: ["ironBoots", "blueTunic", "longshot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "frontLeftHidden",
    title: "Front Left Hidden Wall",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "frontCenterBombable",
    title: "Frong Center Bombable Pit",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "rightHidden",
    title: "Right Hidden Wall",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "centerLargeChest",
    title: "Center Room Large Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "centerSmallChest",
    title: "Center Room Small Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "backLeftBombable",
    title: "Back Left Bombable Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "coffinKey",
    title: "Coffin Key",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "deadHand",
    title: "Dead Hand",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "invisibleChest",
    title: "Invisible Boss Room Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "lullaby", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "underwaterLeftChest",
    title: "Left Under Water Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "underWaterFrontChest",
    title: "Front Under Water Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "basementChest",
    title: "Basement Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lockedPitChest",
    title: "Locked Pitfall Chest",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "behindRightGrate",
    title: "Chest Behind the Fence",
    location: "bottomOfTheWell",
    color: "red",
    requiredItems: ["ocarina", "songOfStorms", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "shadowMap",
    title: "Map Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "shadowCompass",
    title: "Compass Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hoverBootsCheck",
    title: "Hover Boots Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "silverRupeeChest",
    title: "Silver Rupee Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "invisibleBladesChest",
    title: "Invisible Blades Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "invisibleBladesChestHidden",
    title: "Invisible Blades Hidden Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fallingSpikesLower",
    title: "Falling Spikes Lower Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fallingSpikesUpper",
    title: "Falling Spikes Upper Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs", "strength1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fallingSpikesSwitch",
    title: "Falling Spikes Switch Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs", "strength1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "invisibleSpikesChest",
    title: "Invisible Spikes Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "giantPotKey",
    title: "Giant Pot Key",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "windHintChest",
    title: "Chest Near Wind Hint",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "afterWindChest",
    title: "Chest After Wind Hint",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "afterWindChestHidden",
    title: "Hidden Chest After Wind Hint",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "spikeWallsChest",
    title: "Spike Wall Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "shadowBossKey",
    title: "Boss Key",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hiddenFloormasterChest",
    title: "Hidden Floormaster Chest",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "bongo",
    title: "Bongo Bongo",
    location: "shadowTemple",
    color: "red",
    requiredItems: ["ocarina", "nocturn", "hookshot", "magic1", "dinsFire", "lensOfTruth", "hoverBoots", "bombs", "lullaby", "bow"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "gerudoCrate",
    title: "Gerudo Valley Crate Heart Piece",
    location: "gerudoValley",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "gerudoWaterfall",
    title: "Gerudo Valley Waterfall",
    location: "gerudoValley",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: true,
    isChecked: false,
  },
  {
    name: "hammerRockGrotto",
    title: "Chest Behind Hammer Rocks",
    location: "gerudoValley",
    color: "red",
    requiredItems: ["longshot", "hammer"],
    secondaryItems: ["ocarina", "epona", "hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "archery1",
    title: "Archery Game 1",
    location: "gerudoValley",
    color: "red",
    requiredItems: ["ocarina", "epona", "bow"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "archery2",
    title: "Archery Game 2",
    location: "gerudoValley",
    color: "red",
    requiredItems: ["ocarina", "epona", "bow"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "rooftopChest",
    title: "Chest on Fortress Rooftop",
    location: "gerudoValley",
    color: "red",
    requiredItems: ["ocarina", "epona", "hookshot"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lobbyChestLeft",
    title: "Lobby Chest Left",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "bow"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lobbyRightChest",
    title: "Lobby Chest Right",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "bow"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "stalfosChest",
    title: "Stalfos Room Chest",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "beamosChest",
    title: "Beamos Room Chest",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "bombs"],
    secondaryItems: ["longshot", "bombs"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hiddenCeilingChest",
    title: "Hidden Ceiling Chest",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "lensOfTruth", "magic1"],
    secondaryItems: ["longshot", "lensOfTruth", "magic1"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mazePathFirstChest",
    title: "Maze Path Chest 1",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mazePathSecondChest",
    title: "Maze Path Chest 2",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mazePathThirdChest",
    title: "Maze Path Chest 3",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mazePathFinalChest",
    title: "Maze Path Chest Final",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mazeRightCentralChest",
    title: "Maze Right Path 1",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mazeRightSideChest",
    title: "Maze Right Path 2",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mazeRightSideKey",
    title: "Maze Right Path Key",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona"],
    secondaryItems: ["longshot"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "underwaterChest",
    title: "Under Water Silver Rupee Chest",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "ironBoots", "hoverBoots"],
    secondaryItems: ["longshot", "ironBoots", "hoverBoots"],
    ternaryItems: ["ocarina", "epona", "songOfTime", "hookshot", "ironBoots"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hammerRoomChest",
    title: "Hammer Room Chest",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "hookshot", "hammer"],
    secondaryItems: ["longshot", "hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hammerRoomSwitch",
    title: "Hammer Room Switch",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "hookshot", "hammer"],
    secondaryItems: ["longshot", "hammer"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "eyeStatue",
    title: "Eye Statue Chest",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "hookshot", "hammer", "bow"],
    secondaryItems: ["longshot", "hammer", "bow"],
    ternaryItems: ["longshot", "lensOfTruth", "magic", "hoverboots", "bow"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "upperEyeStatue",
    title: "Eye Statue Scarecrow Chest",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["ocarina", "epona", "hookshot", "hammer"],
    secondaryItems: ["longshot", "hammer", "bow", "ocarina"],
    ternaryItems: ["longshot", "lensOfTruth", "magic", "hoverboots"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "beforeBlockChest",
    title: "Chest Before Block",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["longshot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "blockFirstChest",
    title: "Block Room Chest 1",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["longshot", "strength2", "lensOfTruth", "magic1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "blockSecondChest",
    title: "Block Room Chest 2",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["longshot", "strength2", "lensOfTruth", "magic1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "blockThirdChest",
    title: "Block Room Chest 3",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["longshot", "strength2", "lensOfTruth", "magic1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "blockFourthChest",
    title: "Block Room Chest 4",
    location: "gerudoTrainingGround",
    color: "red",
    requiredItems: ["longshot", "strength2", "lensOfTruth", "magic1"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "requiemCheck",
    title: "Requiem of Spirit",
    location: "desert",
    color: "red",
    requiredItems: ["ocarina", "requiem"],
    alternateItems: ["longshot", "lensOfTruth", "magic1"],
    ternaryItems: ["hoverBoots", "lensOfTruth", "magic1"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "wastelandChest",
    title: "Wasteland Chest",
    location: "desert",
    color: "red",
    primaryItems: ["longshot", "lensOfTruth", "magic1", "dinsFire", "fireArrow"],
    secondaryItems: ["hoverBoots", "lensOfTruth", "magic1", "dinsFire", "fireArrow"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "oasisHeartPiece",
    title: "Desert Oasis Heartpiece",
    location: "desert",
    color: "red",
    requiredItems: ["ocarina", "requiem", "beans"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "nayrusLoveCheck",
    title: "Deser Oasis Fairy Fountain",
    location: "Desert Oasis Fairy Fountain",
    color: "red",
    requiredItems: ["ocarina", "requiem", "bombs"],
    alternateItems: ["longshot", "lensOfTruth", "magic1", "bombs"],
    ternaryItems: ["hoverBoots", "lensOfTruth", "magic1", "bombs"],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "childLeftChest",
    title: "Child Section Left Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "slingShot"],
    secondaryItems: ["ocarina", "requiem", "boomerang"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "childRightChest",
    title: "Child Section Right Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "slingShot"],
    secondaryItems: ["ocarina", "requiem", "boomerang"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "spiritCompass",
    title: "Compass Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "hookshot", "lullaby", "strength2"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "spiritMap",
    title: "Map Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "earlyAdultRightChest",
    title: "Early Adult Section Right Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mirrorChestRight",
    title: "Mirror Room Right Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mirrorChestLeft",
    title: "Mirror Room Left Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "childClimbEast",
    title: "Child Climbing Section East",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "slingShot"],
    secondaryItems: ["ocarina", "requiem", "boomerang"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "childClimbNorth",
    title: "Child Climbing Section North",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "slingShot"],
    secondaryItems: ["ocarina", "requiem", "boomerang"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "sunBlockRoom",
    title: "Sun Block Room",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["carina", "requiem", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "silverGauntlets",
    title: "Silver Gauntlets Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["requiem", "ocarina", "bombs"],
    secondaryItems: ["ocarina", "requiem", "strength2"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "statueHandChest",
    title: "Statue Hand Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "NEMainRoomChest",
    title: "Northeast Main Room Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "hoverBoots", "strength2", "requiem", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "mirrorShieldCheck",
    title: "Mirror Shield Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2", "bombs"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "fourArmosChest",
    title: "Chest Near 4 Armos",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2", "bombs", "mirrorShield"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hallwayLeftHiddenChest",
    title: "Hidden Hallway Chest 1",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2", "bombs", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "hallwayRightHiddenChest",
    title: "Hidden Hallway Chest 2",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2", "bombs", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "spiritBossKey",
    title: "Boss Key",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "bow", "hookshot", "hammer", "lullaby", "strength2"],
    secondaryItems: ["ocarina", "requiem", "bow", "hookshot", "bombs", "lullaby", "strength2"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "topChest",
    title: "Top Room Chest",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2", "mirrorShield", "bow"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "twinrova",
    title: "Twinrova",
    location: "spiritTemple",
    color: "red",
    requiredItems: ["ocarina", "requiem", "strength2", "mirrorShield", "bombs", "hookshot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "forestTrial",
    title: "Forest Trial Chest",
    location: "ganonsCastle",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "waterTrial1",
    title: "Water Trial Chest 1",
    location: "ganonsCastle",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "waterTrial2",
    title: "Water Trial Chest 2",
    location: "ganonsCastle",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "shadowTrial1",
    title: "Shadow Trial Chest",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["hookshot"],
    secondaryItems: ["hoverBoots"],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "shadowTrial2",
    title: "Shadow Trial Chest 2",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["hoverBoots", "longShot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "spiritTrial1",
    title: "Spirit Trial Chest 1",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["hookshot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "spiritTrial2",
    title: "Spirit Trial Chest 2",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["bombs", "magic1", "lensOfTruth", "hookShot"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial1",
    title: "Light Trial Chest 1",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial2",
    title: "Light Trial Chest 2",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial3",
    title: "Light Trial Chest 3",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial4",
    title: "Light Trial Chest 4",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial5",
    title: "Light Trial Chest 5",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial6",
    title: "Light Trial Chest 6",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial7",
    title: "Light Trial Invisible Chest",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3", "magic1", "lensOfTruth"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "lightTrial8",
    title: "Light Trial Lullaby Chest",
    location: "ganonsCastle",
    color: "red",
    requiredItems: ["strength3", "ocarina", "lullaby"],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  },
  {
    name: "ganonBossKey",
    title: "Boss Key",
    location: "ganonsCastle",
    color: "red",
    requiredItems: [],
    secondaryItems: [],
    ternaryItems: [],
    isAccessible: false,
    isChecked: false,
  }
]

const itemSeed = [
  {
    name: "bow",
    isObtained: false  
  },
  {
    name: "hookshot",
    isObtained: false
  },
  {
    name: "longshot",
    isObtained: false
  },
  {
    name: "hammer",
    isObtained: false
  },
  {
    name: "bombs",
    isObtained: false
  },
  {
    name: "bombchus",
    isObtained: false
  },
  {
    name: "strength1",
    isObtained: false
  },
  {
    name: "strength2",
    isObtained: false
  },
  {
    name: "strength3",
    isObtained: false
  },
  {
    name: "kokiriSword",
    isObtained: false
  },
  {
    name: "biggoronSword",
    isObtained: false
  },
  {
    name: "dekuShield",
    isObtained: false
  },
  {
    name: "hylianShield",
    isObtained: false
  },
  {
    name: "mirrorShield",
    isObtained: false
  },
  {
    name: "blueTunic",
    isObtained: false
  },
  {
    name: "redTunic",
    isObtained: false
  },
  {
    name: "ironBoots",
    isObtained: false
  },
  {
    name: "hoverBoots",
    isObtained: false
  },
  {
    name: "dinsFire",
    isObtained: false
  },
  {
    name: "faroresWind",
    isObtained: false
  },
  {
    name: "nayrusLove",
    isObtained: false
  },
  {
    name: "magic1",
    isObtained: false
  },
  {
    name: "magic2",
    isObtained: false
  },
  {
    name: "fireArrow",
    isObtained: false
  },
  {
    name: "iceArrow",
    isObtained: false
  },
  {
    name: "lightArrow",
    isObtained: false
  },
  {
    name: "slingShot",
    isObtained: false
  },
  {
    name: "boomerang",
    isObtained: false
  },
  {
    name: "lensOfTruth",
    isObtained: false
  },
  {
    name: "ocarina",
    isObtained: false
  },
  {
    name: "ocarinaOfTime",
    isObtained: false
  },
  {
    name: "rutosNote",
    isObtained: false
  },
  {
    name: "bottle1",
    isObtained: false
  },
  {
    name: "bottle2",
    isObtained: false
  },
  {
    name: "bottle3",
    isObtained: false
  },
  {
    name: "bottle4",
    isObtained: false
  },
  {
    name: "beans",
    isObtained: false
  },
  {
    name: "skullMask",
    isObtained: false
  },
  {
    name: "maskOfTruth",
    isObtained: false
  },
  {
    name: "wallet1",
    isObtained: false
  },
  {
    name: "wallet2",
    isObtained: false
  },
  {
    name: "wallet3",
    isObtained: false
  },
  {
    name: "skull10",
    isObtained: false
  },
  {
    name: "skull20",
    isObtained: false
  },
  {
    name: "skull30",
    isObtained: false
  },
  {
    name: "skull40",
    isObtained: false
  },
  {
    name: "skull50",
    isObtained: false
  },
  {
    name: "lullaby",
    isObtained: false
  },
  {
    name: "epona",
    isObtained: false
  },
  {
    name: "saria",
    isObtained: false
  },
  {
    name: "songOfTime",
    isObtained: false
  },
  {
    name: "songOfStorms",
    isObtained: false
  },
  {
    name: "sunSong",
    isObtained: false
  },
  {
    name: "minuet",
    isObtained: false
  },
  {
    name: "bolero",
    isObtained: false
  },
  {
    name: "serenade",
    isObtained: false
  },
  {
    name: "nocturne",
    isObtained: false
  },
  {
    name: "requiem",
    isObtained: false
  },
  {
    name: "prelude",
    isObtained: false
  },
  {
    name: "emerald",
    isObtained: false
  },
  {
    name: "ruby",
    isObtained: false
  },
  {
    name: "sapphire",
    isObtained: false
  },
  {
    name: "forestMedallion",
    isObtained: false
  },
  {
    name: "fireMedallion",
    isObtained: false
  },
  {
    name: "waterMedallion",
    isObtained: false
  },
  {
    name: "shadowMedallion",
    isObtained: false
  },
  {
    name: "spiritMedallion",
    isObtained: false
  },
  {
    name: "lightMedallion",
    isObtained: false
  }
];

db.Item.remove({})
  .then(() => db.Item.collection.insertMany(itemSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted.");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });

db.Check
  .remove({})
  .then(() => db.Check.collection.insertMany(checkSeed))
  .then(data => {
      console.log(data.result.n + " records inserted.");
      process.exit(0);
  })
  .catch(err => {
      console.error(err);
      process.exit(1)
  });

db.Area.remove({})
  .then(() => db.Area.collection.insertMany(areaSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted.");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
