const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(
    process.env.MONGODB_URI ||
    "mongodb://localhost/ootitemtracker"
  );


const checkSeed = [
    {
      name: "midosHouse",
      title: "Mido's House (4)",
      location: "kokiriForest",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "swordCheck",
      title: "Kokiri Sword Chest",
      location: "kokiriForest",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "songOfStormsGrotto",
      title: "Song of Storms Grotto",
      location: "kokiriForest",
      color: "",
      requiredItems: ["ocarina", "songOfStorms"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "ocarinaCheck",
      title: "Fairy Ocarina",
      location: "kokiriForest",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "dekuMap",
      title: "Map Chest",
      location: "dekuTree",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "dekuCompass",
      title: "Compass Chest",
      location: "dekuTree",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "compassChestSide",
      title: "Compass Room Side Chest",
      location: "dekuTree",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "slingshotCheck",
      title: "Slingshot Chest",
      location: "dekuTree",
      color: "",
      requiredItems: ["dekuShield"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "slingshotChestSide",
      title: "Slingshot Side Chest",
      location: "dekuTree",
      color: "",
      requiredItems: ["dekuShield"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "ghoma",
      title: "Ghoma",
      location: "dekuTree",
      color: "",
      requiredItems: ["dekuShield", "slingShot", "kokiriSword"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "skullKid",
      title: "Skull Kid",
      location: "lostWoods",
      color: "",
      requiredItems: ["ocarina", "saria"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "scrub",
      title: "Scrub Salesman",
      location: "lostWoods",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "memoryGame",
      title: "Ocarina Memory Game",
      location: "lostWoods",
      color: "",
      requiredItems: ["ocarina"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "slingshotTarget",
      title: "Slingshot Target",
      location: "lostWoods",
      color: "",
      requiredItems: ["slingShot"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lostWoodsBombGrotto",
      title: "Bomb Grotto",
      location: "lostWoods",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "scrubGrotto",
      title: "Scrub Salesman Grotto",
      location: "lostWoods",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "wolfosGrotto",
      title: "",
      location: "lostWoods",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "sariaSong",
      title: "Saria's Song",
      location: "lostWoods",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "minuetOfForest",
      title: "Minuet of Forest",
      location: "lostWoods",
      color: "",
      requiredItems: ["ocarina", "minuet", "saria"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "skullMask",
      title: "Deku Theater Skull Mask",
      location: "lostWoods",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "maskOfTruth",
      title: "Deku Theater Mask of Truth",
      location: "lostWoods",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "southGrotto",
      title: "South Grotto",
      location: "hyruleField",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "southScrubGrotto",
      title: "South Scrub Salesman Grotto",
      location: "hyruleField",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "southEastGrotto",
      title: "Southeast Grotto",
      location: "hyruleField",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "northWestGrotto",
      title: "Northwest Grotto",
      location: "hyruleField",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "northGrotto",
      title: "North Grotto",
      location: "hyruleField",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "songOfTimeCheck",
      title: "Song of Time",
      location: "hyruleField",
      color: "",
      requiredItems: ["emerald", "ruby", "sapphire"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "ocarinaOfTimeCheck",
      title: "Ocarina of Time",
      location: "hyruleField",
      color: "",
      requiredItems: ["emerald", "ruby", "sapphire"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "eponasSong",
      title: "Epona's Song",
      location: "lonlonRanch",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "chickenGame",
      title: "Cucco Game",
      location: "lonlonRanch",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "lonlonHeartPiece",
      title: "Lon Lon Heart Piece",
      location: "lonlonRanch",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "lullabyCheck",
      title: "Zelda's Lullaby",
      location: "hyruleMarket",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "childGallery",
      title: "Child Shooting Gallery",
      location: "hyruleMarket",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "bombchuBowling1",
      title: "Bombchu Bowling 1",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "bombchuBowling2",
      title: "Bombchu Bowling 2",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "chestGame",
      title: "Chest Game",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "dogLady",
      title: "Return Monty the Dog",
      location: "hyruleMarket",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "10Poes",
      title: "10 Big Poes",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["bow", "epona", "bottle1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "dinsFireCheck",
      title: "Din's Fire",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer", "ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "healthUpgrade",
      title: "Health Upgrade",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["ocarina", "lullaby", "strength3"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "preludeCheck",
      title: "Prelude of Light",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["forestMedallion"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightArrowCheck",
      title: "Light Arrow Check",
      location: "hyruleMarket",
      color: "",
      requiredItems: ["forestMedallion", "fireMedallion", "waterMedallion", "shadowMedallion", "spiritMedallion", "lightMedallion"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "childChickens",
      title: "Collect Cuccos",
      location: "kakVillage",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "anju",
      title: "Anju as Adult",
      location: "kakVillage",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "BackGrottoChest",
      title: "Back Grotto",
      location: "kakVillage",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "redeadGrotto",
      title: "Redead Grotto",
      location: "kakVillage",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "cowCheck",
      title: "Cow House",
      location: "kakVillage",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "manOnRoof",
      title: "Guy on the Roof",
      location: "kakVillage",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "adultGallery",
      title: "Adult Shooting Gallery",
      location: "kakVillage",
      color: "",
      requiredItems: ["bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "songOfStormsCheck",
      title: "Song of Storms",
      location: "kakVillage",
      color: "",
      requiredItems: ["ocarina"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "windmillHeartPiece",
      title: "Windmill Heat Piece",
      location: "kakVillage",
      color: "",
      requiredItems: ["ocarina", "songOfTime"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "nocturnCheck",
      title: "Nocturn of Shadow",
      location: "kakVillage",
      color: "",
      requiredItems: ["forestMedallion", "fireMedallion", "waterMedallion"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "skull10Check",
      title: "10 Gold Skulltulas",
      location: "kakVillage",
      color: "",
      requiredItems: ["skull10"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "skull20Check",
      title: "20 Gold Skulltulas",
      location: "kakVillage",
      color: "",
      requiredItems: ["skull20"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "skull30Check",
      title: "30 Gold Skulltulas",
      location: "kakVillage",
      color: "",
      requiredItems: ["skull30"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "skull40Check",
      title: "40 Gold Skulltulas",
      location: "kakVillage",
      color: "",
      requiredItems: ["skull40"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "skull50Check",
      title: "50 Gold Skulltulas",
      location: "kakVillage",
      color: "",
      requiredItems: ["skull50"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "dampe1",
      title: "Dampe Race 1",
      location: "graveyard",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "dampe2",
      title: "Dampe Race 2",
      location: "graveyard",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "dampeHeartPiece",
      title: "Dampe Heart Piece",
      location: "graveyard",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "redeadGrave",
      title: "Redead Grave",
      location: "graveyard",
      color: "",
      requiredItems: ["sunSong"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "sunSongCheck",
      title: "Sun Song",
      location: "graveyard",
      color: "",
      requiredItems: ["ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "sunSongChest",
      title: "Sun Song Chest",
      location: "graveyard",
      color: "",
      requiredItems: ["ocarina", "lullaby", "magic1", "dinsFire", "fireArrow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "boxHeartPiece",
      title: "Boxed Heart Piece",
      location: "graveyard",
      color: "",
      requiredItems: ["longshot", "beans"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "leftMaze",
      title: "Left Boulder Maze",
      location: "goronCity",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer", "strength2"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "centerMaze",
      title: "Center Boulder Maze",
      location: "goronCity",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer", "strength2"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "rightMaze",
      title: "Right Boulder Maze",
      location: "goronCity",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer", "strength2"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hotRodder",
      title: "Hot Rodder Goron",
      location: "goronCity",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "linkTheGoron",
      title: "Link The Goron",
      location: "goronCity",
      color: "",
      requiredItems: ["bombs", "bombchus", "strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "spinningPot",
      title: "Spinning Pot Heart Piece",
      location: "goronCity",
      color: "",
      requiredItems: ["ocarina", "lullaby", "bombs", "strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "daruniasJoy",
      title: "Darunia's Joy",
      location: "goronCity",
      color: "",
      requiredItems: ["ocarina", "lullaby", "saria"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "dodongoHeartPiece",
      title: "Above Dodongo's Cavern Heart",
      location: "deathMountain",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "wallChest",
      title: "Chest in Wall",
      location: "deathMountain",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "outsideGoronCityGrotto",
      title: "Outside Goron City Grotto",
      location: "deathMountain",
      color: "",
      requiredItems: ["ocarina", "songOfStorms"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "boleroCheck",
      title: "Bolero of Fire",
      location: "deathMountain",
      color: "",
      requiredItems: ["hookshot", "bolero"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "craterHeartPiece",
      title: "Crater Wall Heart Piece",
      location: "deathMountain",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "magic1Check",
      title: "Magic Upgrade 1",
      location: "deathMountain",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "magic2Check",
      title: "Magic Upgrade 2",
      location: "deathMountain",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "craterBeanHeartPiece",
      title: "Crater Magic Bean Heart Piece",
      location: "deathMountain",
      color: "",
      requiredItems: ["beans"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "craterGrotto",
      title: "Crater Grotto",
      location: "deathMountain",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "bigGoronSword",
      title: "Big Goron Sword",
      location: "deathMountain",
      color: "",
      requiredItems: ["claimCheck"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "dodongoMap",
      title: "Map Chest",
      location: "dodongosCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "dodongoCompass",
      title: "Compass Chest",
      location: "dodongosCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "bombPlatform",
      title: "Platform Before Bombs",
      location: "dodongosCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "bombBagChest",
      title: "Bomb Bag Chest",
      location: "dodongosCavern",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "endOfBridgeChest",
      title: "End of Bridge Chest",
      location: "dodongosCavern",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "chestAboveDodongo",
      title: "Chest Above King Dodongo",
      location: "dodongosCavern",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "kingDodongo",
      title: "King Dodongo",
      location: "dodongosCavern",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "riverGrotto",
      title: "River Grotto",
      location: "zorasRiver",
      color: "",
      requiredItems: ["bombs", "bombchus", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "southHeartPiece",
      title: "South HeartPiece",
      location: "zorasRiver",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "northHeartPiece",
      title: "North HeartPiece",
      location: "zorasRiver",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "frogs1",
      title: "Frogs (Song of Storms)",
      location: "zorasRiver",
      color: "",
      requiredItems: ["ocarina", "songOfStorms"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "frogs2",
      title: "Frogs (songs)",
      location: "zorasRiver",
      color: "",
      requiredItems: ["ocarina", "lullaby", "epona", "songOfTime", "sunSong"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "divingMinigame",
      title: "Diving Minigame",
      location: "zorasDomain",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "kingZora",
      title: "King Zora Thawed",
      location: "zorasDomain",
      color: "",
      requiredItems: ["bottle1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "torchRun",
      title: "Torch Run",
      location: "zorasDomain",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "faroresWindCheck",
      title: "Zora Fairy Fountain",
      location: "zorasFountain",
      color: "",
      requiredItems: ["bombs", "bombchus", "ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "iceBerg",
      title: "Iceberg Heart Piece",
      location: "zorasFountain",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "underWaterHeartPiece",
      title: "Under Water Heart Piece",
      location: "zorasFountain",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "boomerangCheck",
      title: "Boomerang Chest",
      location: "jabu",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "jabuMap",
      title: "Map Chest",
      location: "jabu",
      color: "",
      requiredItems: ["boomeraing"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "jabuCompass",
      title: "Compass Chest",
      location: "jabu",
      color: "",
      requiredItems: ["boomerang"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "barinade",
      title: "Barinade",
      location: "jabu",
      color: "",
      requiredItems: ["boomerang"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fireArrowCheck",
      title: "Fire Arrows",
      location: "lakeHylia",
      color: "",
      requiredItems: ["bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "rutosBottleCheck",
      title: "Ruto's Bottle",
      location: "lakeHylia",
      color: "",
      requiredItems: ["silverScale"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "bottomOfTheLab",
      title: "Bottom of the Lab",
      location: "lakeHylia",
      color: "",
      requiredItems: ["goldScale"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "childFishing",
      title: "Child Fishing",
      location: "lakeHylia",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "adultFishing",
      title: "Adult Fishing",
      location: "lakeHylia",
      color: "",
      requiredItems: ["ocarina", "hookshot"],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "lobbyChest",
      title: "First Lobby Chest",
      location: "forestTemple",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "chestBehindLobby",
      title: "Chest Behind the Lobby",
      location: "forestTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "wellChest",
      title: "Well Chest",
      location: "forestTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "forestMapChest",
      title: "Map Chest",
      location: "forestTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "forrestCompass",
      title: "Compass Chest",
      location: "forestTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "outdoorHookshot",
      title: "Outdoor Chest on the Hill",
      location: "forestTemple",
      color: "",
      requiredItems: ["bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fallingRoomChest",
      title: "Falling Ceiling Chest",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "forrestBossKey",
      title: "Boss Key Chest",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "blockPushChest",
      title: "Block Pushing Chest",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "floorMasterChest",
      title: "Floor Master Room",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "bowCheck",
      title: "Bow Chest",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "redPoe",
      title: "Red Poe Chest",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "bluePoe",
      title: "Blue Poe Chest",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "bossRoomChest",
      title: "Chest Outside Boss Room",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "phantomGanon",
      title: "Phantom Ganon",
      location: "forestTemple",
      color: "",
      requiredItems: ["strength1", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "chestNearBoss",
      title: "Chest Near Boss",
      location: "fireTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "flareDancerChest",
      title: "Flare Dancer Chest",
      location: "fireTemple",
      color: "",
      requiredItems: ["hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fireBossKey",
      title: "Boss Key",
      location: "fireTemple",
      color: "",
      requiredItems: ["hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lavaRoomLeftChest",
      title: "Lava Room Left Chest",
      location: "fireTemple",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lavaRoomRightChest",
      title: "Lava Room Right Chest",
      location: "fireTemple",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "boulderMazeLower",
      title: "Lower Boulder Maze",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "BoulderMazeUpper",
      title: "Upper Boulder Maze",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "BoulderMazeSide",
      title: "Side/Upper Boulder Maze",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "BoulderMazePit",
      title: "Boulder Maze Bombable Pit",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "scarecrowChest",
      title: "Scarecrow Upper Chest",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1", "ocarina", "hookshot"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fireMap",
      title: "Map Chest",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fireCompass",
      title: "Fire Compass",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "highestGoronChest",
      title: "Highest Goron Chest",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1", "songOfTime", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hammerCheck",
      title: "Hammer Chest",
      location: "fireTemple",
      color: "",
      requiredItems: ["strength1", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "volvagia",
      title: "Volvagia",
      location: "fireTemple",
      color: "",
      requiredItems: ["hookshot", "bombs", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "iceMap",
      title: "Map Chest",
      location: "iceCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "iceCompass",
      title: "Compass Chest",
      location: "iceCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "iceHeartPiece",
      title: "Ice Cavern Heart Piece",
      location: "iceCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "ironBootsCheck",
      title: "Iron Boots",
      location: "iceCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "serenadeCheck",
      title: "Serenade of Water",
      location: "iceCavern",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "waterMap",
      title: "Map Chest",
      location: "waterTemple",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "waterCompass",
      title: "Compass Chest",
      location: "waterTemple",
      color: "",
      requiredItems: [],
      isAccessible: true,
      isChecked: false,
    },
    {
      name: "torchChest",
      title: "Torch Chest",
      location: "waterTemple",
      color: "",
      requiredItems: ["bow", "ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "dragonChest",
      title: "Dragon Room Chest",
      location: "waterTemple",
      color: "",
      requiredItems: [ "ocarina", "lullaby", "songOfTime"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "centralTargetChest",
      title: "Central Bow Target Chest",
      location: "waterTemple",
      color: "",
      requiredItems: ["strength1", "longshot", "bow", "ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "waterBossKey",
      title: "Boss Key",
      location: "waterTemple",
      color: "",
      requiredItems: ["strength1", "longshot", "ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "centralPillarChest",
      title: "Central Pillar Sunken Chest",
      location: "waterTemple",
      color: "",
      requiredItems: ["ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "crackedWallChest",
      title: "Cracked Wall Chest",
      location: "waterTemple",
      color: "",
      requiredItems: ["ocarina", "lullaby", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "darkLink",
      title: "Dark Link",
      location: "waterTemple",
      color: "",
      requiredItems: ["ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "riverChest",
      title: "River Chest",
      location: "waterTemple",
      color: "",
      requiredItems: ["ocarina", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "morpha",
      title: "Morpha",
      location: "waterTemple",
      color: "",
      requiredItems: ["longshot"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "frontLeftHidden",
      title: "Front Left Hidden Wall",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["magic1", "lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "frontCenterBombable",
      title: "Frong Center Bombable Pit",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "rightHidden",
      title: "Right Hidden Wall",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["magic1", "lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "centerLargeChest",
      title: "Center Room Large Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["magic1", "lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "centerSmallChest",
      title: "Center Room Small Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["magic1", "lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "backLeftBombable",
      title: "Back Left Bombable Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "coffinKey",
      title: "Coffin Key",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "deadHand",
      title: "Dead Hand",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "invisibleChest",
      title: "Invisible Boss Room Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["lullaby", "magic1", "lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "underwaterLeftChest",
      title: "Left Under Water Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "underWaterFrontChest",
      title: "Front Under Water Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "basementChest",
      title: "Basement Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["bombs", "bombchus"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lockedPitChest",
      title: "Locked Pitfall Chest",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["magic1", "lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "behindRightGrate",
      title: "Chest Behind the Fence",
      location: "bottomOfTheWell",
      color: "",
      requiredItems: ["magic1", "lensOfTruth"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "shadowMap",
      title: "Map Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "shadowCompass",
      title: "Compass Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hoverBootsCheck",
      title: "Hover Boots Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "silverRupeeChest",
      title: "Silver Rupee Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "invisibleBladesChest",
      title: "Invisible Blades Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "invisibleBladesChestHidden",
      title: "Invisible Blades Hidden Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fallingSpikesLower",
      title: "Falling Spikes Lower Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fallingSpikesUpper",
      title: "Falling Spikes Upper Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fallingSpikesSwitch",
      title: "Falling Spikes Switch Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "strength1"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "invisibleSpikesChest",
      title: "Invisible Spikes Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "giantPotKey",
      title: "Giant Pot Key",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "windHintChest",
      title: "Chest Near Wind Hint",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "afterWindChest",
      title: "Chest After Wind Hint",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "afterWindChestHidden",
      title: "Hidden Chest After Wind Hint",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "spikeWallsChest",
      title: "Spike Wall Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "shadowBossKey",
      title: "Boss Key",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hiddenFloormasterChest",
      title: "Hidden Floormaster Chest",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "bongo",
      title: "Bongo Bongo",
      location: "shadowTemple",
      color: "",
      requiredItems: ["hoverBoots", "bombs", "lullaby"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "gerudoCrate",
      title: "Gerudo Valley Crate Heart Piece",
      location: "gerudoValley",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "gerudoWaterfall",
      title: "Gerudo Valley Waterfall",
      location: "gerudoValley",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hammerRockGrotto",
      title: "Chest Behind Hammer Rocks",
      location: "gerudoValley",
      color: "",
      requiredItems: ["longshot", "ocarina", "epona", "hammer"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "archery1",
      title: "Archery Game 1",
      location: "gerudoValley",
      color: "",
      requiredItems: ["ocarina", "epona", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "archery2",
      title: "Archery Game 2",
      location: "gerudoValley",
      color: "",
      requiredItems: ["ocarina", "epona", "bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "rooftopChest",
      title: "Chest on Fortress Rooftop",
      location: "gerudoValley",
      color: "",
      requiredItems: ["ocarina", "hookshot", "longshot"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lobbyChestLeft",
      title: "Lobby Chest Left",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: ["bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lobbyRightChest",
      title: "Lobby Chest Right",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: ["bow"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "stalfosChest",
      title: "Stalfos Room Chest",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "beamosChest",
      title: "Beamos Room Chest",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: ["bombs"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hiddenCeilingChest",
      title: "Hidden Ceiling Chest",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mazePathFirstChest",
      title: "Maze Path Chest 1",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mazePathSecondChest",
      title: "Maze Path Chest 2",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mazePathThirdChest",
      title: "Maze Path Chest 3",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mazePathFinalChest",
      title: "Maze Path Chest Final",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mazeRightCentralChest",
      title: "Maze Right Path 1",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mazeRightSideChest",
      title: "Maze Right Path 2",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mazeRightSideKey",
      title: "Maze Right Path Key",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "underwaterChest",
      title: "Under Water Silver Rupee Chest",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hammerRoomChest",
      title: "Hammer Room Chest",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: ["longshot"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hammerRoomSwitch",
      title: "Hammer Room Switch",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "eyeStatue",
      title: "Eye Statue Chest",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "upperEyeStatue",
      title: "Eye Statue Scarecrow Chest",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "beforeBlockChest",
      title: "Chest Before Block",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: ["longshot"],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "blockFirstChest",
      title: "Block Room Chest 1",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "blockSecondChest",
      title: "Block Room Chest 2",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "blockThirdChest",
      title: "Block Room Chest 3",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "blockFourthChest",
      title: "Block Room Chest 4",
      location: "gerudoTrainingGround",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "requiemCheck",
      title: "Requiem of Spirit",
      location: "desert",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "wastelandChest",
      title: "Wasteland Chest",
      location: "desert",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "oasisHeartPiece",
      title: "Desert Oasis Heartpiece",
      location: "desert",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "nayrusLoveCheck",
      title: "Deser Oasis Fairy Fountain",
      location: "Desert Oasis Fairy Fountain",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "childLeftChest",
      title: "Child Section Left Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "childRightChest",
      title: "Child Section Right Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "spiritCompass",
      title: "Compass Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "spiritMap",
      title: "Map Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "earlyAdultRightChest",
      title: "Early Adult Section Right Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mirrorChestRight",
      title: "Mirror Room Right Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mirrorChestLeft",
      title: "Mirror Room Left Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "childClimbEast",
      title: "Child Climbing Section East",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "childClimbNorth",
      title: "Child Climbing Section North",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "sunBlockRoom",
      title: "Sun Block Room",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "silverGauntlets",
      title: "Silver Gauntlets Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "statueHandChest",
      title: "Statue Hand Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "NEMainRoomChest",
      title: "Northeast Main Room Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "mirrorShieldCheck",
      title: "Mirror Shield Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "fourArmosChest",
      title: "Chest Near 4 Armos",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hallwayLeftHiddenChest",
      title: "Hidden Hallway Chest 1",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "hallwayRightHiddenChest",
      title: "Hidden Hallway Chest 2",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "spiritBossKey",
      title: "Boss Key",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "topChest",
      title: "Top Room Chest",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "twinrova",
      title: "Twinrova",
      location: "spiritTemple",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "forestTrial",
      title: "Forest Trial Chest",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "waterTrial1",
      title: "Water Trial Chest 1",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "waterTrial2",
      title: "Water Trial Chest 2",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "shadowTrial1",
      title: "Shadow Trial Chest",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "shadowTrial2",
      title: "Shadow Trial Chest 2",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "spiritTrial1",
      title: "Spirit Trial Chest 1",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "spiritTrial2",
      title: "Spirit Trial Chest 2",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial1",
      title: "Light Trial Chest 1",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial2",
      title: "Light Trial Chest 2",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial3",
      title: "Light Trial Chest 3",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial4",
      title: "Light Trial Chest 4",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial5",
      title: "Light Trial Chest 5",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial6",
      title: "Light Trial Chest 6",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial7",
      title: "Light Trial Invisible Chest",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "lightTrial8",
      title: "Light Trial Lullaby Chest",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    },
    {
      name: "ganonBossKey",
      title: "Boss Key",
      location: "ganonsCastle",
      color: "",
      requiredItems: [],
      isAccessible: false,
      isChecked: false,
    }
  ]

db.Check
    .remove({})
    .then(() => db.Check.collection.insertMany(checkSeed))
    .then(data => {
        console.log(data.result.n + " records inserted.");
        process.exit(0);
    })
    .catch(err => {
        console.error(err);
        process.exit(1)
    });
